#!/usr/bin/env python3

from subprocess import Popen, DEVNULL
from shutil import copytree
from os import environ


# # =x= CLIENT =x=
# CLIENT_PATH = "/root/structs.sh/client"

# print("[client] building client")
# npm = Popen(["npm", "run", "build"], cwd=CLIENT_PATH, stdout=DEVNULL, stderr=DEVNULL)
# npm.wait()

# print("[client] copying files to www directory")
# copytree(f"{CLIENT_PATH}/build", "/var/www/html/", dirs_exist_ok=True)
# # ---


# =x= DEBUGGER =x=
DEBUGGER_PATH = "/root/structs.sh/debugger"
VENV_PYTHON_PATH = "/root/pyenv/bin/python3"

print("[debugger] starting debugger server")
env = environ.copy()
env["PYTHONPATH"] = "/root/pyenv/lib/python3.11/site-packages/:."
debugger = Popen(
    [VENV_PYTHON_PATH, f"{DEBUGGER_PATH}/src/server.py"],
    env=env,
    cwd=DEBUGGER_PATH,
)
debugger.wait()
# ---
