Enter number of vertices: Enter number of edges: Enter edges in the form v-w: 
Graph: nV = 12
Edges:
 0: 0-3 0-8 0-10
 1: 1-5 1-9
 2: 2-10
 3: 3-0 3-8
 4: 4-6 4-7 4-11
 5: 5-1 5-9
 6: 6-4
 7: 7-4
 8: 8-0 8-3
 9: 9-1 9-5
10: 10-0 10-2
11: 11-4

Enter the source vertex: Number of vertices reachable from vertex 2: 5
Enter the source vertex: Number of vertices reachable from vertex 1: 3
Enter the source vertex: Number of vertices reachable from vertex 4: 4
Enter the source vertex: 