Enter number of vertices: Enter number of edges: Enter edges in the form v-w: 
Graph: nV = 11
Edges:
 0: 0-5
 1: 1-2 1-3 1-4
 2: 2-1 2-3 2-4
 3: 3-1 3-2 3-4
 4: 4-1 4-2 4-3
 5: 5-0 5-6
 6: 6-5 6-7
 7: 7-6 7-8
 8: 8-7 8-9
 9: 9-8 9-10
10: 10-9

Enter the source vertex: Number of vertices reachable from vertex 3: 4
Enter the source vertex: Number of vertices reachable from vertex 9: 7
Enter the source vertex: 