FROM node:14-alpine

WORKDIR /app

COPY package.json .

RUN yarn install

COPY . . 

CMD ["yarn", "start"]

# TODO: Should add a production-grade server rather than using the dev server for production
