import gql from 'graphql-tag';

export const questionTypeDefs = gql`
  type ComponentData {
    "Row index that this component is positioned at"
    row: Int
    "Column index that this component is positioned at"
    col: Int
    "Width of the component in number of cells"
    width: Int
    "Height of the component in number of cells"
    height: Int
    "Name of the component. Eg. 'image', 'text', etc."
    componentName: String
    "Stringified JSON containing all the component-specific data"
    data: String
  }

  type Question {
    "The unique identifier for a Question"
    _id: String
    # "Unique identifier for the lesson this is part of"
    # lessonId: String
    "The components that are rendered by GalacticEd's component renderer for this question."
    data: [ComponentData]
    "The message to display when the correct answer has been entered."
    correctMessage: String
  }

  input ComponentDataInput {
    "Unique identifier for a component within a question. Generated by the client"
    id: String
    "Row index that this component is positioned at"
    row: Int
    "Column index that this component is positioned at"
    col: Int
    "Width of the component in number of cells"
    width: Int
    "Height of the component in number of cells"
    height: Int
    "Name of the component. Eg. 'image', 'text', etc."
    componentName: String
    "Stringified JSON containing all the component-specific data"
    data: String
  }

  input CreateQuestionInput {
    # "Unique identifier for the lesson this is part of"
    # lessonId: String
    # "The components that are rendered by GalacticEd's component renderer for this question."
    # components: [CreateComponentInput]
    "The data for the list of UI components rendered on the lesson experience grid"
    data: [ComponentDataInput]
    "The message to display when the correct answer has been entered."
    correctMessage: String
  }

  input UpdateQuestionInput {
    "The unique identifier for a Question"
    _id: String
    "Unique identifier for the lesson this is part of"
    lessonId: String
    "The components that are rendered by GalacticEd's component renderer for this question."
    components: [CreateComponentInput]
    "The message to display when the correct answer has been entered."
    correctMessage: String
  }
`;
