/* -------------------------------------------------------------------------- */
/*                        Swagger Documentation Schemas                       */
/* -------------------------------------------------------------------------- */
// This file contains all the schema definitions you see on autogenerated Swagger docs.
// These schemas are reusable in documentation through the `$ref` operator (you'll see
// them around in the OpenAPI docs for the route handlers).
// These schemas were written based off the data models diagram.

/* ---------------------------------- User ---------------------------------- */
/**
 * This is the schema definition for a User object. This will appear in the auto-generated
 * Swagger documentation and can be referenced in the documentation for endpoints with the path:
 *     '#/components/schemas/Quiz'
 *
 * @swagger
 * components:
 *  schemas:
 *      User:
 *          type: object
 *          properties:
 *              username:
 *                  type: string
 *                  description: A unique public-facing name.
 *              email:
 *                  type: string
 *                  description: The email address associated with this user's account.
 *              password:
 *                  type: string
 *                  description: The encrypted/hashed password for this account.
 */

/* ---------------------------------- Topic --------------------------------- */
/**
 * This is the schema definition for a Topic object. This will appear in the auto-generated
 * Swagger documentation and can be referenced in the documentation for endpoints with the path:
 *     '#/components/schemas/Lesson'
 *
 * @swagger
 * components:
 *  schemas:
 *      Topic:
 *          type: object
 *          properties:
 *              title:
 *                  type: string
 *                  description: Name of the topic, eg. 'Linked Lists'.
 *              description:
 *                  type: string
 *                  description: Description of the topic, eg. 'a linear collection of data elements'.
 *              courses:
 *                  type: array
 *                  items: string
 *                  description: The courses that this topic belongs to, eg. ["COMP1511", "COMP2521"]
 */

/* --------------------------------- Lesson --------------------------------- */
/**
 * This is the schema definition for a Lesson object. This will appear in the auto-generated
 * Swagger documentation and can be referenced in the documentation for endpoints with the path:
 *     '#/components/schemas/Lesson'
 *
 * @swagger
 * components:
 *  schemas:
 *      Lesson:
 *          type: object
 *          required:
 *              - rawMarkdown
 *              - creatorId
 *              - quizzes
 *          properties:
 *              topicId:
 *                  type: string
 *                  description: ID of the topic this lesson is for.
 *              rawMarkdown:
 *                  type: string
 *                  description: The raw markdown source code used to display the content in this lesson.
 *              creatorId:
 *                  type: string
 *                  description: The ID of the user who created this lesson.
 *              quizzes:
 *                  type: array
 *                  items:
 *                      $ref: '#/components/schemas/Quiz'
 */

/* ---------------------------------- Quiz ---------------------------------- */
/**
 * This is the schema definition for a Quiz object. This will appear in the auto-generated
 * Swagger documentation and can be referenced in the documentation for endpoints with the path:
 *     '#/components/schemas/Quiz'
 *
 * @swagger
 * components:
 *  schemas:
 *      Quiz:
 *          type: object
 *          properties:
 *              questionType:
 *                  type: string
 *                  description: The type of the quiz. Eg. 'mc' for multiple choice, 'qa' for question-answer
 *              question:
 *                  type: string
 *                  description: The stringified JSON for the quiz details.
 *              answer:
 *                  type: string
 *                  description: The stringified JSON for the quiz answers.
 */
