Enter number of vertices: Enter number of edges: Enter edges in the form v-w: 
Graph: nV = 6
Edges:
 0: 0-1
 1: 1-0 1-2
 2: 2-1 2-3
 3: 3-2 3-4
 4: 4-3 4-5
 5: 5-4

Enter two vertices: The shortest distance between vertices 0 and 0 is: 0
Enter two vertices: The shortest distance between vertices 0 and 3 is: 3
Enter two vertices: The shortest distance between vertices 4 and 0 is: 4
Enter two vertices: The shortest distance between vertices 1 and 5 is: 4
Enter two vertices: 