Enter number of vertices: Enter number of edges: Enter edges in the form v-w: 
Graph: nV = 10
Edges:
 0: 0-1 0-2
 1: 1-0 1-3 1-6
 2: 2-0 2-9
 3: 3-1 3-4 3-5
 4: 4-3
 5: 5-3 5-7 5-9
 6: 6-1
 7: 7-5 7-8
 8: 8-7
 9: 9-2 9-5

Enter two vertices: The shortest distance between vertices 0 and 7 is: 4
Enter two vertices: The shortest distance between vertices 8 and 2 is: 4
Enter two vertices: The shortest distance between vertices 2 and 6 is: 3
Enter two vertices: The shortest distance between vertices 4 and 9 is: 3
Enter two vertices: The shortest distance between vertices 1 and 9 is: 3
Enter two vertices: The shortest distance between vertices 8 and 0 is: 5
Enter two vertices: The shortest distance between vertices 3 and 9 is: 2
Enter two vertices: The shortest distance between vertices 5 and 6 is: 3
Enter two vertices: 