Enter number of vertices: Enter number of edges: Enter edges in the form v-w: 
Graph: nV = 11
Edges:
 0: 0-1 0-5 0-8 0-10
 1: 1-0 1-2
 2: 2-1 2-3
 3: 3-2 3-4
 4: 4-3
 5: 5-0 5-6
 6: 6-5 6-7
 7: 7-6
 8: 8-0 8-9
 9: 9-8
10: 10-0

Enter the source vertex and maximum distance: numWithin(g, 0, 5) = 11
Enter the source vertex and maximum distance: numWithin(g, 0, 4) = 11
Enter the source vertex and maximum distance: numWithin(g, 0, 3) = 10
Enter the source vertex and maximum distance: numWithin(g, 0, 2) = 8
Enter the source vertex and maximum distance: numWithin(g, 0, 1) = 5
Enter the source vertex and maximum distance: numWithin(g, 0, 0) = 1
Enter the source vertex and maximum distance: numWithin(g, 4, 5) = 8
Enter the source vertex and maximum distance: numWithin(g, 7, 4) = 7
Enter the source vertex and maximum distance: numWithin(g, 9, 3) = 6
Enter the source vertex and maximum distance: numWithin(g, 10, 2) = 5
Enter the source vertex and maximum distance: 