Enter number of vertices: Enter number of edges: Enter edges in the form v-w: 
Graph: nV = 11
Edges:
 0: 0-1 0-2 0-6 0-7
 1: 1-0 1-2
 2: 2-0 2-1 2-3 2-5
 3: 3-2 3-4
 4: 4-3
 5: 5-2
 6: 6-0 6-7
 7: 7-0 7-6 7-8 7-10
 8: 8-7 8-9
 9: 9-8
10: 10-7

Enter the source vertex and maximum distance: numWithin(g, 0, 1) = 5
Enter the source vertex and maximum distance: numWithin(g, 0, 2) = 9
Enter the source vertex and maximum distance: numWithin(g, 0, 3) = 11
Enter the source vertex and maximum distance: numWithin(g, 0, 4) = 11
Enter the source vertex and maximum distance: numWithin(g, 1, 1) = 3
Enter the source vertex and maximum distance: numWithin(g, 1, 2) = 7
Enter the source vertex and maximum distance: numWithin(g, 1, 3) = 10
Enter the source vertex and maximum distance: numWithin(g, 1, 4) = 11
Enter the source vertex and maximum distance: numWithin(g, 4, 1) = 2
Enter the source vertex and maximum distance: numWithin(g, 4, 2) = 3
Enter the source vertex and maximum distance: numWithin(g, 4, 3) = 6
Enter the source vertex and maximum distance: numWithin(g, 4, 4) = 8
Enter the source vertex and maximum distance: numWithin(g, 4, 5) = 10
Enter the source vertex and maximum distance: numWithin(g, 4, 6) = 11
Enter the source vertex and maximum distance: 