Enter number of vertices: Enter number of edges: Enter edges in the form v-w: 
Graph: nV = 19
Edges:
 0: 0-1 0-7
 1: 1-0 1-2 1-8
 2: 2-1 2-3
 3: 3-2 3-4 3-11
 4: 4-3 4-5
 5: 5-4 5-6 5-10
 6: 6-5 6-7
 7: 7-0 7-6 7-9
 8: 8-1 8-9 8-11
 9: 9-7 9-8 9-10
10: 10-5 10-9 10-11
11: 11-3 11-8 11-10
12: 12-13 12-14 12-15 12-17
13: 13-12 13-14 13-15
14: 14-12 14-13 14-15 14-16
15: 15-12 15-13 15-14 15-18
16: 16-14
17: 17-12
18: 18-15

Enter the source vertex and maximum distance: numWithin(g, 0, 4) = 12
Enter the source vertex and maximum distance: numWithin(g, 0, 3) = 11
Enter the source vertex and maximum distance: numWithin(g, 0, 2) = 7
Enter the source vertex and maximum distance: numWithin(g, 8, 3) = 12
Enter the source vertex and maximum distance: numWithin(g, 8, 2) = 9
Enter the source vertex and maximum distance: numWithin(g, 8, 1) = 4
Enter the source vertex and maximum distance: numWithin(g, 12, 2) = 7
Enter the source vertex and maximum distance: numWithin(g, 16, 2) = 5
Enter the source vertex and maximum distance: numWithin(g, 13, 2) = 7
Enter the source vertex and maximum distance: numWithin(g, 13, 1) = 4
Enter the source vertex and maximum distance: 