from python:3.13.3-bookworm

workdir /app

run apt-get update -y
run apt-get install -y gdb

copy requirements.txt .
run pip3 install -r requirements.txt --root-user-action=ignore

copy . .
expose 8000
run echo 'UkNSe2NsaWNrX2NsaWNrX2NsaWNrfQo=' | base64 -d > flag
cmd ["python3", "src/serve.py"]
