FROM ubuntu

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y; apt-get install -y build-essential gdb curl git libssl-dev zlib1g-dev \
    libbz2-dev libreadline-dev libsqlite3-dev \
    libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

# Install python3 to run the backend server
RUN curl https://pyenv.run | bash

ENV HOME="/root"
ENV PYENV_ROOT="${HOME}/.pyenv"
ENV PATH="${PYENV_ROOT}/bin:${PATH}"

ENV PYTHON_VERSION=3.11.3

RUN pyenv install ${PYTHON_VERSION}
RUN pyenv global ${PYTHON_VERSION}

WORKDIR /app

COPY requirements.txt .
RUN pyenv exec pip3 install -r requirements.txt

COPY . .

EXPOSE 5001

CMD ["pyenv", "exec", "python3", "src/server.py"]
