FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

# Set up APT custom configurations
RUN echo "Acquire::http::Pipeline-Depth 0;" > /etc/apt/apt.conf.d/99custom && \
    echo "Acquire::http::No-Cache true;" >> /etc/apt/apt.conf.d/99custom && \
    echo "Acquire::BrokenProxy true;" >> /etc/apt/apt.conf.d/99custom

# Install dependencies
RUN apt-get update && apt-get upgrade -y --fix-missing \
    && apt-get install -y \
    build-essential \
    gdb \
    curl \
    git \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libxml2-dev \
    libxmlsec1-dev \
    libffi-dev \
    liblzma-dev \
    python3 \
    python3-pip \
    python3-venv \
    python-is-python3 \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Setup pyenv and install Python
ENV HOME="/root"
ENV PYENV_ROOT="$HOME/.pyenv"
ENV PATH="$PYENV_ROOT/bin:$PATH"

RUN curl https://pyenv.run | bash && \
    pyenv install 3.11.3 && \
    pyenv global 3.11.3

# Install Python packages in a virtual environment
COPY requirements.txt .
RUN python3 -m venv /venv && \
    /venv/bin/pip install --upgrade pip && \
    /venv/bin/pip install -r requirements.txt

# Setup nvm and install Node.js
ENV NODE_VERSION=20.0.0
ENV NVM_DIR="$HOME/.nvm"
ENV PATH="$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH"

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash && \
    . "$NVM_DIR/nvm.sh" && \
    nvm install $NODE_VERSION && \
    nvm use $NODE_VERSION && \
    nvm alias default $NODE_VERSION

# Install global npm packages
RUN npm install -g nodemon

WORKDIR /app
COPY . .

EXPOSE 8000

# Command to run the application
CMD ["/venv/bin/python3", "-u", "src/server.py"]
