Enter number of vertices: Enter number of edges: Enter edges in the form v-w: 
Graph: nV = 13
Edges:
 0: 0-5
 1: 1-2 1-3 1-4
 2: 2-1 2-3 2-4 2-12
 3: 3-1 3-2 3-4
 4: 4-1 4-2 4-3
 5: 5-0 5-6
 6: 6-5 6-7
 7: 7-6 7-8
 8: 8-7 8-9 8-10
 9: 9-8
10: 10-8 10-11
11: 11-10
12: 12-2

Enter the source vertex: Furthest vertex reachable from vertex 2: 12
Enter the source vertex: Furthest vertex reachable from vertex 3: 12
Enter the source vertex: Furthest vertex reachable from vertex 10: 0
Enter the source vertex: Furthest vertex reachable from vertex 6: 11
Enter the source vertex: Furthest vertex reachable from vertex 7: 11
Enter the source vertex: 