name: Pre-Merge Checks

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependency
        working-directory: ./client
        run: npm install
      - name: TypeScript
        working-directory: ./client
        run: npm run tsc
      - name: Lint
        working-directory: ./client
        run: npm run lint
      - name: Build
        working-directory: ./client
        run: npm run build
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        working-directory: debugger
      - name: Install debugger dependencies
        working-directory: debugger
        run: uv sync --locked --all-extras --dev
      - run: uv format --check
        working-directory: debugger
      - run: uv run mypy src/
        working-directory: debugger


